### ISSUE TITLE
Theme switch styling

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Senior-Project#15]
I'm pretty garbage at styling with css so I noticed the theme switch isn't in the spot I want it to be (far right) on my main monitor but it is on my second monitor where I was initially setting it up. Any help with this would be appreciated.

**Comment by KyleStrout** [comment]
> Considering the theme switch, It's weird if only the editor changes themes but the rest of the app stays light. I think we should either remove the switch or place it in the app bar and have it change the theme of the entire app.

I like this idea

**Comment by jdriscoll98** [comment]
Same I think light/dark mode would be a nice feature to have. Should be easy to do with the theme provider stuff.

**Comment by KyleStrout** [comment]
WIP https://github.com/KyleStrout/Senior-Project/pull/40
