### ISSUE TITLE
Handle error if user rejects deployment

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Senior-Project#28]
If the user rejects deploying the smart contract through Metamask, we need a way to handle the corresponding error.

**Error:**
![image](https://user-images.githubusercontent.com/62024550/153939790-f975ec38-e5d3-42fd-ba93-de5d08d62675.png)

**Comment by jdriscoll98** [comment]
We don't really need to handle this, it doesn't break the app in anyway i don't think
