### ISSUE TITLE
Connect to Wallet flow

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Senior-Project#29]
If the user clicks the "Connect to Wallet" button and doesn't have Metamask installed, they should be alerted that it's not installed and be directed to the Metamask install page. 

Here's some useful documentation for that:
https://docs.metamask.io/guide/create-dapp.html#basic-action-part-1

**Comment by KyleStrout** [comment]
Here's another error that happens when accessing the app and not being logged into Metamask, but having it installed.

![image](https://user-images.githubusercontent.com/62024550/153997349-27edb5e0-35c6-40f2-82b8-5c8debd2a0ff.png)

**Comment by jdriscoll98** [comment]
Yupp we definitley need something to tell them how to get metamask, maybe even reaplce "connect to wallet" with "Install Metamask" if its not installed

**Comment by jdriscoll98** [comment]
I think this issue was for #37 so I'll be looking into it over the weekend

**Comment by jdriscoll98** [comment]
Checking this out now 👍

**Comment by KyleStrout** [comment]
Resolved https://github.com/KyleStrout/Senior-Project/pull/39
