### ISSUE TITLE
Deploy button disabled

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Senior-Project#30]
We can still deploy the contract if the compilation has errors. Do we want to keep the deploy button enabled at all times since it doesn't really matter @jdriscoll98 ? I think you mentioned changing that.

**Comment by KyleStrout** [comment]
If you switch from one codeditor page to another after compiling, the compilerData doesn't change and if you hit deploy, its deploying the previous contract.

**Comment by jdriscoll98** [comment]
If it has errors we might want to disable it so that they don't waste gas fees

**Comment by jdriscoll98** [comment]
will look into the compiler data bug
