### ISSUE TITLE
Cleanup compiler output

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Senior-Project#35]
We can style/reorganize the compiler output to be easier on the eyes. Could use a list of accordions similar to transaction history or something else.

What do you guys think? @jdriscoll98 @CWilson123 @colinnaehr

**Comment by jdriscoll98** [comment]
I kind of like the JSON output over the list of accordions for the compiler output. If @CWilson123 @colinnaehr think it should be prettier though i'll support it 👍
