### ISSUE TITLE
Yarn and Package.json lock files? 

### ISSUE THREAD

**Issue by jdriscoll98** [KyleStrout/Senior-Project#43]
Currently we have yarn.lock file and a package-lock.json. Those are both package managers but we should only have one. I prefer to use npm over yarn because of familiarity, does anyone have a preference?

**Comment by jdriscoll98** [comment]
I think most of our dependencies were installed with npm so it makes sense to keep the package-lock.json instead of the yarn.lock

**Comment by jdriscoll98** [comment]
On second thought, we may need to use yarn. I'm trying to get it to deploy using Vercel (https://vercel.com/dashboard) and it seems like it wants to use yarn. I'll add my findings here.

**Comment by KyleStrout** [comment]
I prefer npm too, I think I used some yarn commands when trying to figure out the problems with web3/config overrides.

**Comment by jdriscoll98** [comment]
I think we're gonna have to use yarn to work with Vercel
