### ISSUE TITLE
Result doesn't show objects/lists?

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Senior-Project#66]
I was adding content for mappings and the result of people is supposed to show all data from the person object at id 2. Which should be name: "Henry" and age: "25" but it only showed the name

![image](https://user-images.githubusercontent.com/62024550/162383232-2ad4afad-7bbd-4599-9a8d-06c0bc129265.png)

**Comment by jdriscoll98** [comment]
hmm i'll look into this one.

**Comment by KyleStrout** [comment]
https://github.com/KyleStrout/Senior-Project/pull/77
