### ISSUE TITLE
Expansion for constructor arguments

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Senior-Project#68]
Right now we only have one text field for constructor arguments. If there's many arguments, then it's hard for the user to see all the different ones they need to add in the text field. Would be better if we had a drop down or expanded area for the arguments.

**Comment by jdriscoll98** [comment]
on it

**Comment by jdriscoll98** [comment]
#72

**Comment by jdriscoll98** [comment]
need to redo the onSubmit function accept values from multiple fields

**Comment by jdriscoll98** [comment]
merged
